In [1]:
import torch

Let's see few basic tensor manipulation. First, just a few of the way to create tensors

In [2]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

y = torch.zeros(4, 3)
print(y)

x = torch.zeros(8,6)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


Above, we create 5x3 matrix filled with zero, and query data type to find out hte zero are 32-bit floating point number, which is default pytorch.
what if you wanted integers instead? uou can always override the default:

In [3]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)


x1 = torch.ones(5,3)
print(x1)
print(x1.dtype)

x2 = torch.ones(20,15)
print(x2)
print(x2.dtype)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

you can see that when we do change the default, the tensor helpfully reports this when printed.
it's come to initilize learning weight randomly, often with a specific seed for the PRNG for reproducibility of reusults:

In [4]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

# the result of this piece of code is different because here no manual_seed
r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\n Shouls match r1:')
print(r3)

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

 Shouls match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


PyTorch tensors perform arithmetic operations intuitively. Tensors of similsr shapes may be added, multiplied, etc. Operation with scaler and distributed over the tensor;

In [5]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

Here's a small sample of the mathematical operations available:

In [6]:
r = torch.rand(2, 2) - 0.5 * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# comman mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonomatric functions
print('\nInverse sine of r')
print(torch.asin(r))

# ...and linear algebra operatins like determinant and singular value decompstion 
print('\n Detrminant of r')
print(torch.det(r))
print('\nSingular value decompostion of r:')
print(torch.svd(r))

# ...and statiistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.0022, -0.6116],
        [-0.3071, -0.8297]])

Absolute value of r:
tensor([[0.0022, 0.6116],
        [0.3071, 0.8297]])

Inverse sine of r
tensor([[-0.0022, -0.6581],
        [-0.3122, -0.9785]])

 Detrminant of r
tensor(-0.1860)

Singular value decompostion of r:
torch.return_types.svd(
U=tensor([[-0.5599, -0.8286],
        [-0.8286,  0.5599]]),
S=tensor([1.0611, 0.1753]),
V=tensor([[ 0.2410, -0.9705],
        [ 0.9705,  0.2410]]))

Average and standard deviation of r:
(tensor(0.3608), tensor(-0.4376))

Maximum value of r:
tensor(-0.0022)
