# PyTorch Tensors

Tensors are the central data abstraction in PyTorch. This interactive notebook provides an in-depth introduction to the `torch.Tensor` class. You can run this notebook locally, on [Colab](https://colab.research.google.com/), or on your preferred cloud service.

First things first, let's import the PyTorch module. We'll also add Python's math module to facilitate some of the examples.

In [1]:
import torch
import math

## Creating Tensors
The simplest way to create a tensor is with the `torch.empty()` call:

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Let's unpack what we just did:

* We created a tensor using one of the numerous factory methods attached to the `torch` module.
* The tensor itself is 2-dimensional, having 3 rows and 4 columns.
* The type of the object returned is `torch.Tensor`, which is an alias for `torch.FloatTensor`; by default, PyTorch tensors are populated with 32-bit floating point numbers. (More on data types below.)
* You will probably see some random-looking values when printing your tensor. The `torch.empty()` call allocates memory for the tensor, but does not initialize it with any values - so what you're seeing is whatever was in memory at the time of allocation.

A brief note about tensors and their number of dimensions, and terminology:
* You will sometimes see a 1-dimensional tensor called a *vector.*
* Likewise, a 2-dimensional tensor is often referred to as a *matrix.*
* Anything with more than two dimensions is generally just called a tensor.

More often than not, you'll want to initialize your tensor with some value. Common cases are all zeros, all ones, or random values, and the `torch` module provides factory methods for all of these:

In [3]:
zero = torch.zeros(2, 3)
print(zero)


ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


The factory methods all do just what you'd expect - we have a tensor full of zeros, another full of ones, and another with random values between 0 and 1.

### Random Tensors and Seeding

Speaking of the random tensor, did you notice the call to `torch.manual_seed()` immediately preceding it? Initializing tensors, such as a model's learning weights, with random values is common but there are times - especially in research settings - where you'll want some assurance of the reproducibility of your results. Manually setting your random number generator's seed is the way to do this. Let's look more closely:

In [4]:
torch.manual_seed(1729)
random1 = torch.rand(3, 4)
print(random1)

random2 = torch.rand(3, 4)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(3, 4)
print(random3)

random4 = torch.rand(3, 4)
print(random4)

tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938]])
tensor([[0.6128, 0.1519, 0.0453, 0.5035],
        [0.9978, 0.3884, 0.6929, 0.1703],
        [0.1384, 0.4759, 0.7481, 0.0361]])
tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938]])
tensor([[0.6128, 0.1519, 0.0453, 0.5035],
        [0.9978, 0.3884, 0.6929, 0.1703],
        [0.1384, 0.4759, 0.7481, 0.0361]])


What you should see above is that `random1` and `random3` carry identical values, as do `random2` and `random4`. Manually setting the RNG's seed resets it, so that identical computations depending on random number should, in most settings, provide identical results.

For more information, see the [PyTorch documentation on reproducibility](https://pytorch.org/docs/stable/notes/randomness.html).

### Tensor Shapes
Often, when you're performing operations on two or more tensors, they will need to be of the same *shape* - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the `torch.*_like()` methods:

In [5]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

random_like_x = torch.rand_like(x)
print(random_like_x.shape)
print(random_like_x)



torch.Size([2, 2, 3])
tensor([[[ 1.1703e+26,  4.5722e-41, -1.3057e+01],
         [ 3.0718e-41,  1.4013e-45,  0.0000e+00]],

        [[-1.3037e+01,  3.0718e-41, -1.3074e+01],
         [ 3.0718e-41,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[ 1.1703e+26,  4.5722e-41, -1.2905e+01],
         [ 3.0718e-41,  1.4013e-45,  0.0000e+00]],

        [[-1.3037e+01,  3.0718e-41, -1.3074e+01],
         [ 3.0718e-41,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0.5062, 0.8469, 0.2588],
         [0.2707, 0.4115, 0.6839]],

        [[0.0703, 0.5105, 0.9451],
         [0.2359, 0.1979, 0.3327]]])


The first new thing in the code cell above is the use of the `.shape` property on a tensor. This property contains a list of the extent of each dimension of a tensor - in our case, `x` is a three-dimensional tensor with shape 2 x 2 x 3.

Below that, we call the `.empty_like()`, `.zeros_like()`, `.ones_like()`, and `.rand_like()` methods. Using the `.shape` property, we can verify that each of these methods returns a tensor of identical dimensionality and extent.

The last way to create a tensor that will cover is to specify its data directly from a PyTorch collection:

In [6]:
some_constant = torch.tensor([[1.01034, 0.12783], [3.14523, 0.23456]])
print(some_constant.shape)
print(type(some_constant))
print(some_constant)

some_integer = torch.tensor((1, 3, 2, 7, 8, 9, 10, 45, 55))
print(some_integer.shape)
print(type(some_integer))
print(some_integer)

more_integer = torch.Tensor(((1, 5, 7, 2, 10), [2, 6, 99, 65, 78]))
print(more_integer.shape)
print(type(more_integer))
print(more_integer)




torch.Size([2, 2])
<class 'torch.Tensor'>
tensor([[1.0103, 0.1278],
        [3.1452, 0.2346]])
torch.Size([9])
<class 'torch.Tensor'>
tensor([ 1,  3,  2,  7,  8,  9, 10, 45, 55])
torch.Size([2, 5])
<class 'torch.Tensor'>
tensor([[ 1.,  5.,  7.,  2., 10.],
        [ 2.,  6., 99., 65., 78.]])


Using `torch.tensor()` is the most straightforward way to create a tensor if you already have data in a Python tuple or list. As shown above, nesting the collections will result in a multi-dimensional tensor.

*Note: `torch.tensor()` creates a copy of the data.*

### Tensor Data Types
Setting the datatype of a tensor is possible a couple of ways:

In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.zeros((3, 4), dtype=torch.int64) * 20.
print(b)

c = b.to( torch.int32)
print(c)


tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


The simplest way to set the underlying data type of a tensor is with an optional argument at creation time. In the first line of the cell above, we set `dtype=torch.int16` for the tensor `a`. When we print `a`, we can see that it's full of `1` rather than `1.` - Python's subtle cue that this is an integer type rather than floating point.

Another thing to notice about printing `a` is that, unlike when we left `dtype` as the default (32-bit floating point), printing the tensor also specifies its `dtype`.

You may have also spotted that we went from specifying the tensor's shape as a series of integer arguments, to grouping those arguments in a tuple. This is not strictly necessary - PyTorch will take a series of initial, unlabeled integer arguments as a tensor shape - but when adding the optional arguments, it can make your intent more readable.

The other way to set the datatype is with the `.to()` method. In the cell above, we create a random floating point tensor `b` in the usual way. Following that, we create `c` by converting `b` to a 32-bit integer with the `.to()` method. Note that `c` contains all the same values as `b`, but truncated to integers.

Available data types include:

* `torch.bool`
* `torch.int8`
* `torch.uint8`
* `torch.int16`
* `torch.int32`
* `torch.int64`
* `torch.half`
* `torch.float`
* `torch.double`
* `torch.bfloat`

## Math & Logic with PyTorch Tensors

Now that you know some of the ways to create a tensor... what can you do with them?

Let's look at basic arithmetic first, and how tensors interact with simple scalars:

In [8]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 -1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)


tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


As you can see above, arithmetic operations between tensors and scalars, such as addition, subtraction, multiplication, division, and exponentiation are distributed over every element of the tensor. Because the output of such an operation will be a tensor, you can chain them together with the usual operator precedence rules, as in the line where we create `threes`.

Similar operations between two tensors also behave like you'd intuitively expect:

In [9]:
powers2s = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2s)
fives = fours + ones
print(fives)
dozens = fours * threes
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


It's important to note here that all of the tensors in the previous code cell were of identical shape. What happens when we try to perform a binary operation on tensors if dissimilar shape?

**Note: The following cell throws a run-time error. This is intentional.**

In [10]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In the general case, you cannot operate on tensors of different shape this way, even in a case like the cell above, where the tensors have an identical number of elements.

### In Brief: Tensor Broadcasting

*(Note: If you are familiar with broadcasting semantics in NumPy ndarrays, you'll find the same rules apply here.)*

The exception to the same-shapes rule is *tensor broadcasting.* Here's an example:

In [11]:
rand = torch.rand(2, 4)
double = rand * (torch.ones(1, 4) * 2)

print(rand)
print(double)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


What's the trick here? How is it we got to multiply a 2x4 tensor by a 1x4 tensor?

Broadcasting is a way to perform an operation between tensors that have similarities in their shapes. In the example above, the one-row, four-column tensor is multiplied by *both rows* of the two-row, four-column tensor.

This is an important operation in Deep Learning. The common example is multiplying a tensor of learning weights by a *batch* of input tensors, applying the operation to each instance in the batch separately, and returning a tensor of identical shape - just like our (2, 4) * (1, 4) example above returned a tensor of shape (2, 4).

The rules for broadcasting are:

* Each tensor must have at least one dimension - no empty tensors.
* Comparing the dimension sizes of the two tensors, *going from last to first:*
* * Each dimension must be equal, *or*
* * One of the dimensions must be of size 1, *or*
* * The dimension does not exist in one of the tensors

Tensors of identical shape, of course, are trivially "broadcastable", as you saw earlier.

Here are some examples of situations that honor the above rules and allow broadcasting:

In [12]:
a = torch.ones(4, 3, 2)
print(a)

b = a * torch.rand(  3, 2) # 2nd & 3rd dim is identical
print(b)

c = a * torch.rand(  3, 1) # 2nd is idetical but 3rd is different
print(c)

d = a * torch.rand(  1, 2) #3rd dim is identical & 2nd is different
print(d)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]]])
tensor([[[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]]])
tensor([[[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444,

Look closely at the values of each tensor above:
* The multiplication operation that created `b` was broadcast over every "layer" of `a`.
* For `c`, the operation was broadcast over ever layer and row of `a` - every 3-element column is identical.
* For `d`, we switched it around - now every *row* is identical, across layers and columns.

For more information on broadcasting, see the [PyTorch documentation](https://pytorch.org/docs/stable/notes/broadcasting.html) on the topic.

Here are some examples of attempts at broadcasting that will fail:

**Note: The following cell throws a run-time error. This is intentional.**

In [13]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(4, 3) # dimention must match last to first
print(b)

c = a * torch.rand(  2, 3) # 2nd & 3rd dimention are same
print(c)

d = a * torch.rand((0, )) # can't broadcast with zeros
print(d)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

### More Math with Tensors

PyTorch tensors have over three hundred operations that can be performed on them.

Here is a small sample from some of the major categories of operations:

In [54]:
# Comman Function
a = torch.rand(5, 8) * 2 -1

print("Absolute function",torch.abs(a))
print('ceil function ',torch.ceil(a))
print('floor function',torch.floor(a))
print('clamp function',torch.clamp(a, -0.5, 0.5))

# Trignometric function and their inverse

angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print(angles)
sines = torch.sin(angles)
print(sines)
inverse = torch.asin(sines) # sin inverse
print(inverse)

# bitwise operation
print('\nBitwise operation XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([5, 8, 12])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\n Broadcasted, element_wise equality comparison: ')
d = torch.tensor([[1. ,2.],[3., 4.]])
e = torch.ones(1, 2)  #many comparison ops support Broadcasting
print(torch.eq(d, e))  # return a tensor of type bool

# reduction
print('\nReductions ops')
print(torch.max(d))          # returns a single-element tensor
print(torch.max(d).item())   # extracts the value from the returned tensor
print(torch.mean(d))         # average
print(torch.std(d))          # standard deviation
print(torch.prod(d))         # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operation
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.],[0., 3.]])  # three times identity matrix

print('\n Vector and Metrices ')
print(torch.cross(v1, v2)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print('print m1',m1)
m3 = torch.matmul(m1, m2)
print('print m3',m3)               # 3 times m1
print('print svd',torch.svd(m3))    # singular value decomposition

Absolute function tensor([[0.4948, 0.7943, 0.2600, 0.8975, 0.0576, 0.9441, 0.0567, 0.3615],
        [0.5941, 0.2787, 0.9871, 0.9055, 0.2031, 0.3874, 0.3988, 0.7187],
        [0.8166, 0.6246, 0.3942, 0.0696, 0.9207, 0.7248, 0.3910, 0.5289],
        [0.1493, 0.0166, 0.2272, 0.3383, 0.5263, 0.7173, 0.0353, 0.0388],
        [0.0714, 0.5624, 0.0722, 0.2601, 0.1423, 0.6060, 0.8075, 0.4949]])
ceil function  tensor([[-0., -0., -0., 1., 1., -0., 1., -0.],
        [-0., 1., -0., -0., -0., 1., 1., 1.],
        [-0., -0., -0., 1., 1., 1., 1., -0.],
        [-0., -0., -0., -0., 1., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0., -0., -0.]])
floor function tensor([[-1., -1., -1.,  0.,  0., -1.,  0., -1.],
        [-1.,  0., -1., -1., -1.,  0.,  0.,  0.],
        [-1., -1., -1.,  0.,  0.,  0.,  0., -1.],
        [-1., -1., -1., -1.,  0., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1., -1.]])
clamp function tensor([[-0.4948, -0.5000, -0.2600,  0.5000,  0.0576, -0.5000,  0.0567, -0.3